import { get_greeting } from "$gleam/lib/greet.mjs";
import { useSignal } from "@preact/signals";
import Counter from "../islands/Counter.tsx";

export default function Home() {
  const count = useSignal(0);
  const greeting = get_greeting("Hello from Gleam!");

  return (
    <div class="px-4 py-8 mx-auto bg-[#86efac]">
      <div class="max-w-screen-md mx-auto flex flex-col items-center justify-center">
        <h1 class="text-4xl font-bold">Welcome to fresh_gleam</h1>
        <p class="my-4">
          {greeting}
        </p>
        <p class="my-4">
          The above message was generated by a server-side Gleam function.
        </p>
        <Counter count={count} />
      </div>
    </div>
  );
}
