name: Test
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Gleam
        uses: gleam-lang/setup-gleam@v1.0.1
        with:
          gleam-version: 1.5.0

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.46.3

      - name: Run tests
        run: "deno task test"
